djangopackages/djangopackages

static/css/oc.css
templates/grid/grid_detail.html

I think sticky table header is more convenient, especially on big scrollable grids

add sticky table header on grid page

---

grid/views.py
package/models.py
searchv2/models.py
static/css/base.css
static/css/oc.css
templates/_homepage.html
templates/base.html
templates/grid/grid_detail.html
templates/package/category.html
templates/package/includes/_package.html
templates/package/includes/_package_no_link.html
templates/package/package.html
templates/package/package_list.html
templates/py3_compat.html

The color of the star icon is just a guess... I'm not a designer.

change repo watchers and its icon to stars fixes #295

---

docs/introduction.rst

GoogleCode is closed and SourceForge is almost dead

Remove Google/SourceForge from introduction.rst

---

.gitignore
.idea/djangopackages.iml
.idea/inspectionProfiles/Project_Default.xml
.idea/misc.xml
.idea/modules.xml
.idea/vcs.xml

Support PyCharm

---

dev.yml
docker-compose.yml

Switch from links to depends_on for the django service from dev.yml.
Closes #477.

Favor depends_on over links for django service

---

package/migrations/0002_packageexample_created_by.py
package/models.py
package/tests/initial_data.py
package/tests/test_views.py
package/urls.py
package/views.py
searchv2/tests/test_views.py
static/css/oc.css
templates/package/delete_example.html
templates/package/edit_example.html
templates/package/package.html

Ability to delete PackageExample only by creator of the PackageExample as discussed with @audreyr on Twitter

Delete package example

---

CONTRIBUTORS.txt

Add Rexhep Berlajolli (rexhepberlajolli) at contributors

Add rexhepberlajolli to contributors

---

docs/contributing.rst

In line 28 corrected sentence by removing "on our" as there was a typo mistake

Sentence correction in line 28

---

requirements.txt
settings/docker.py

Removed opbeat as it deprecreated and doesn't support **Python 3**

remove opbeat

---

README.rst

This PR fixes https://github.com/djangopackages/djangopackages/issues/573

Fix contributors link

---

compose/postgres/Dockerfile
dev.yml

This PR fixes long due **Travis** build failure

Fix travis build failure

---

.github/workflows/actions.yml
.travis.yml

Our goal is to switch from Travis to GitHub Actions CI and then to used GitHub's Container Registry to automate deployments.

💚  Adds GitHub Actions CI

---

pytest.ini
requirements.in
requirements.txt
settings/base.py
settings/docker.py
settings/test.py
wsgi.py

Related to #631 
The goal here is to make sure we don't have any lingering third-party service accounts.

🚜  Transition any paid service accounts

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json
.devcontainer/docker-compose.yml
.github/workflows/actions.yml
.vscode/launch.json

:whale: Adds devcontainer files

---

apiv4/serializers.py

🐛 Fixes empty model serializer fields

---

requirements.in
requirements.txt
settings/base.py

✨  Adds django-waffle

---

apiv3/urls.py
core/apiv2.py
core/models.py
feeds/urls.py
grid/models.py
grid/urls.py
grid/utils.py
homepage/models.py
package/models.py
package/urls.py
package/views.py
profiles/models.py
profiles/urls.py
profiles/views.py
reports/urls.py
searchv2/models.py
searchv2/urls.py
urls.py

This PR lays down some groundwork for moving to Django 3.2 LTS by dropping support for unsupported features.

🚜 Drops older Django support

---

apiv4/admin.py
apiv4/models.py
apiv4/serializers.py
apiv4/viewsets.py
core/decorators.py
core/fields.py
core/management/commands/big_email_send.py
core/tests/datautil.py
docs/conf.py
fabfile.py
feeds/models.py
homepage/tests/test_views.py
package/management/commands/package_updater.py
package/management/commands/pypi_updater.py
package/repos/github.py
package/repos/gitlab.py
package/tests/test_models.py
package/tests/test_repos.py
package/views.py
profiles/views.py
reports/models.py
searchv2/builders.py
searchv2/models.py
settings/docker.py
urls.py

This pull request audits and removes unused imports.

:fire: Cleanup unused import statements

---

requirements.in
requirements.txt

This is an attempt to prune down unnecessary python packages which are installed but not used.

🔥  Remove unused third party packages

---

apiv3/tests/test_package.py
core/test_utils/context_managers.py
docs/deployment/docker.rst
docs/reference.rst
grid/tests/test_views.py
package/repos/base_handler.py

Command used: `codespell --skip=./static,./collected_static,*.conf,*.json --write-changes .`

:pencil: Applies codespell

---

apiv4/admin.py
grid/admin.py
homepage/admin.py
package/admin.py
profiles/admin.py
searchv2/admin.py

:tractor: Admin refactor to add raw_id_fields and other options

---

fabfile.py
searchv2/builders.py
searchv2/management/commands/searchv2_build.py
templates/_homepage.html

Friday Night Bug Fixes and Updates

---

homepage/views.py
package/admin.py
templates/pages/open.html
urls.py

Still figuring this out, but I suspect some elements will make their way into features from this.

:sparkles: Add Open page

---

settings/base.py
settings/test.py
urls.py

This is an extension of #698 
Fixes  #685

698 debug follow up

---

requirements.txt

:arrow_up: Updates pip requirements

---

.devcontainer/devcontainer.json
.devcontainer/docker-compose.yml
.vscode/extensions.json

This updated our dev container setup via Twitter feedback to troubleshoot some VS Code + Pylance weirdness.

:whale: :gear: Adds vscode-server extension mount + refactor

---

package/models.py

:bug: Fix for Incorrect PyPI URLs on some packages 

---

settings/base.py

Invalid profile url in ABSOLUTE_URL_OVERRIDES

---

templates/package/package.html

Show PyPi in sidebar only if PyPi URL exists.

---

package/management/commands/package_updater.py

This should help in addressing #728

Log a meaningful error message instead of raising an exception.

---

package/management/commands/pypi_find_missing.py

Partial fix for #721
We also need to re-build how the pypi link is created.

✨  Adds management command to help find missing pypi packages

---

README.rst
compose/postgres/Dockerfile
compose/postgres/healthcheck_pg.sh
dev.yml

This pull-request was made on top of #755 and requires it to be merged first

Add healthcheck to the docker-compose dev.yml

---

package/management/commands/cleanup_github_projects.py

This creates a management command to start addressing GitHub package cleanup. Fixes #772

:pencil: Quick cleanup script for #772

---

.devcontainer/devcontainer.json
requirements.in
requirements.txt
settings/docker.py

🔨  2022-02-18 Friday updates

---

package/models.py

:bug: Fixes #786 License is blank

---

conftest.py
grid/tests/fixtures.py
grid/tests/test_models.py
package/models.py
package/tests/fixtures.py
package/tests/test_models.py
package/tests/test_models_v2.py

Adding some fixtures and some other workarounds for packages.

✏️  2022-02-18 Friday Updates 3

---

package/tests/test_repos.py

:tractor: Changes out Django for Deps

---

grid/management/commands/fix_grid_element.py
homepage/views.py
package/forms.py
package/management/commands/cleanup_github_projects.py
package/management/commands/package_updater.py
package/management/commands/pypi_updater.py
package/models.py
package/repos/base_handler.py
package/repos/bitbucket.py
package/templatetags/package_tags.py
package/utils.py
package/views.py
scripts/update_contributors.py

Refactored some code to simplify without readability taking a hit
* Also makes use of `f-string` and `walrus` operator

Refactor code

---

package/management/commands/audit_textfield_max_length.py

:sparkles: Audit script to find records with max_length > 500

---

package/tests/fixtures.py
package/tests/test_repos.py
package/tests/test_repos_bitbucket.py
package/tests/test_repos_github.py
package/tests/test_repos_gitlab.py

Verifies #703 and refactors `test_repos*` files.

Add tests for Archived GitHub Projects and refactors Repos tests 

---

package/views.py
templates/package/python3_list.html

This is a recent Sentry bug that was happening on ?page=100 then started causing some other issues.

:green_heart: Fix /python3/ page

---

package/tests/test_views.py
package/views.py
settings/test.py

If not for this bug, Sentry would be happy.

:bug: Fix for /python3/ sorting options

---

package/tests/test_models.py
requirements.txt

Mostly security and health updates to all of our packages.

:arrow_up: Bumps Django and other deps for security updates

---

requirements.txt

:arrow_up: Upgrades to Django 4.0.7 and other deps

---

homepage/tests/test_views.py
homepage/views.py
settings/docker.py
urls.py

Adding some caching to help the homepage and various pages.

🔥 Add more caching

---

apiv4/serializers.py
templates/search/search_partial.html

:pencil: Emoji fix for title and description fields

---

requirements.txt

Mostly a forced Django 4.1.1 upgrade

:arrow_up: Upgrades Deps

---

grid/views.py
package/tests/test_repos.py

:bug: Temp fix for patch scoring

---

justfile

Mostly there but kind of rough still. 
cc @ryancheley

:gear: Adds justfile

---

static/css/oc.css
templates/_homepage.html

Allowing users to see the 50 latest packages more easily
Fixes #645

Added View More

---

grid/views.py

Ref:
https://github.com/djangopackages/djangopackages/blob/e4806a86a51c71f1a62f5c61d8353adc679f53fe/templates/grid/grid_detail.html#L142

Fix N+1 Query on Grid Detail Page [`package.category`]

---

package/tests/test_views.py

This is meant to lock down our query counts so we can set some performance goals.

💚  Add assert num queries to packages

---

.env.local.example
fabfile.py
requirements.in
requirements.txt

Fixes #759 
Long overdue fix for busting our Cloudflare cache. 
I would add this to the deploy process, but I'm not sure we want it to run unless the cache is actually changed.

:fire: Purge Cloudflare cache

---

homepage/views.py
tests/test_views.py

This PR reduces Number of Database queries from **37** to **12** on `OpenView`.

Optimize `OpenView` Database Query

---

package/management/commands/check_package_examples.py

:sparkles: Adds check_package_examples

---

grid/urls.py
grid/views.py
package/management/commands/opengraph_image_export.py
package/urls.py
package/views.py
templates/grid/grid_opengraph.html
templates/package/package_opengraph.html

:sparkles: Adds opengraph templates and views for Packages and Grids

---

CODE_OF_CONDUCT.md

Feel free to ping me if you want added  to the list. I'll probably recruiter a few people so it's not just me since these feels weird with one person on it.

📝 Adding COC since I didn't realize it was missing one

---

justfile

✏️ Fix typo

---

.pre-commit-config.yaml
docs/install.md
docs/install_opinionated.md
justfile

:pencil: Adds pre-commit info to docs

---

requirements.in
requirements.txt

See https://github.com/django-crispy-forms/django-crispy-forms/releases/tag/2.0 for breaking changes

:pushpin: Pin django-crispy-forms<2

---

docs/conf.py
docs/contributing.md
docs/deployment.md
docs/faq.md
docs/install.md
docs/install_opinionated.md
docs/management_commands.md
docs/requirements.in
docs/requirements.txt
docs/testing_instructions.md

Adds `sphinx-copybutton` support for all terminal commands.

:books: Add sphinx copybutton

---

core/templatetags/page_metadata_tags.py
grid/models.py
package/models.py
templates/grid/grid_detail.html
templates/grid/grid_opengraph.html
templates/includes/page_metadata.html
templates/package/package.html
templates/package/package_opengraph.html

:art: Adjust opengraph previews

---

templates/grid/grid_detail.html
templates/grid/grid_detail_landscape.html
templates/includes/page_metadata.html
templates/package/includes/_package.html
templates/package/includes/_package_no_link.html
templates/package/package.html
templates/profiles/profile.html
templates/search/search_partial.html

Fixes #926 
I think we should audit and globally fix some of these to make sure everything gets processed.

:pencil: Updates description formatting

---

docker-compose.yml
requirements.in
requirements.txt

Quick overview of how to run docs:
```shell
docker-compose --profiles=docs up
```
This will run mkdocs on port 4000

Adds mkdocs service to docker compose

---

.github/workflows/actions.yml

:gear: exclude docs folder

---

tests/conftest.py
tests/test_viewsets.py

Tests Generated using: https://github.com/saadmk11/drf-test-generator :)

Add Tests for APIv4

---

apiv3/tests/data.py
apiv3/tests/test_package.py
fabfile.py
package/management/commands/cleanup_github_projects.py
package/management/commands/pypi_updater.py
package/models.py
products/management/commands/import_products.py
settings/base.py
templates/_homepage.html
templates/grid/grid_opengraph.html
templates/package/package_opengraph.html
templates/readiness/readiness_detail.html

- Updates opencomparison 
- template linting
- removes unused settings
- updates pypi_updater and cleanup_github_projects management commands to handle status code errors better

:hammer: Friday updates

---

templates/base.html

Fix NavBar Button Hover Issue

---

docker-compose.override.yml.example
docker-compose.prod.yml
docker-compose.yml
fabfile.py
homepage/views.py
justfile

🚀  DO Droplet cleanup and documentation

---

docker-compose.yml
dockerfiles/django/Dockerfile
dockerfiles/django/Dockerfile-dev

This update is to build out a better build cache for the production server and removes container names that might trip a few people up.

:whale: Docker cleanup

---

grid/tables.py
grid/tests/test_views.py
grid/views.py

Reference: https://github.com/djangopackages/djangopackages/issues/965

Add Active Packages Column to Grid List View and Reduce DB Query Count

---

dockerfiles/redis/Dockerfile
justfile
requirements.in
requirements.txt
settings/base.py

Fixes #1021 #1026 #1025 
Our/my bus factor finally kicked in without Sentry messages making it to me. I was down with the flu for four days and then was mostly offline with my youngest having a minor procedure and came back to seeing an update broke something. 
We can re-assess and figure out how to make it easier to see these and fix them so it's not just deployed from my machine. 
Thanks for jumping in on these.

:package: Adds crispy-bootstrap3 (hotfix)

---

docs/requirements.txt

This PR has a few security updates, including `urlib3`.

:arrow_up: Bumps deps

---

grid/urls.py
package/tables.py
package/tests/test_views.py
package/views.py
templates/grid/grid_detail.html
templates/package/grid_packages.html
templates/package/package_list.html

> * [ ]  Grids could link to a flatter list of all packages including inactive Grids (Scores that are <=0)
Reference:
- https://github.com/djangopackages/djangopackages/issues/965

Add Grid Packages List View

---

docs/docs/deployment.md

django-q was introduced in #1007
utility was introduced in #1005

📝 Added docs for django-q and utility

---

dockerfiles/django/Dockerfile
dockerfiles/django/Dockerfile-dev

:whale: Adds build-essentials to fix uwsgi build

---

grid/tests/test_views.py
package/tests/test_views.py
static/bower_components/bootstrap/_includes/ads.html
templates/grid/grid_detail.html
templates/package/category.html
templates/package/grid_packages.html
templates/package/package.html
templates/package/python3_list.html
templates/pages/open.html

- :pencil: Updates costs/income for 2023
- :fire: Removes Carbon Ads #1086

:sparkles: Friday updates

---

docs/docs/rules/rules.md
docs/mkdocs.yml

📝 Clean up for nav display

---

templates/robots.txt
tests/test_views.py
urls.py

:sparkles: Adds robots.txt file

---

settings/docker.py

Reference: https://docs.sentry.io/platforms/python/profiling/

Enable Sentry Profiling

---

templates/pages/stack.html
urls.py

This is a First Draft of the stack page for djangopackages. We may want to consider putting this on docs.djangopackages.org if that's more appropriate.
@jefftriplett @ryancheley Feel free to add any suggestion regarding the wording or if I have missed any service we are using. 
closes https://github.com/djangopackages/djangopackages/issues/1132

Add Tech Stack Page

---

justfile
pyproject.toml

Fixes #1118 
This has virtually no impact on anything but is a clean-up PR.

:broom: Target version cleanup

---

blog/feeds.py
blog/managers.py
blog/models.py
blog/urls.py

I needed this to help glue some social media things together.

:sparkles: Add feeds to the Changelog

---

docs/docs/contributing.md

Fix for issue https://github.com/djangopackages/djangopackages/issues/1171

contributing docs fix

---

package/forms.py

fix for issue https://github.com/djangopackages/djangopackages/issues/1162

documentation_url field added

---

feeds/tests/data.py

:green_heart: Removes pk’s from load data

---

package/tests/test_fetch_pypi_data.py

Adds tests for #1180 to test that one permutation of pypi's documentation URLs is found.

:green_heart: Adds tests for documentation_url

---

templates/base.html

[Issue #1169](https://github.com/djangopackages/djangopackages/issues/1169)

Add changelog pre-footer link

---

grid/forms.py
templates/grid/grid_detail.html

:art: Updates filter layout

---

favorites/models.py

Fixes https://github.com/djangopackages/djangopackages/issues/1207

use F field

---

searchv2/tests/test_views.py

fixes https://github.com/djangopackages/djangopackages/issues/1205

tests for opensearch

---

package/admin.py

fixes https://github.com/djangopackages/djangopackages/issues/1210

package_admin favorite_count

---

compose.yml
dockerfiles/django/Dockerfile
dockerfiles/django/Dockerfile-dev
dockerfiles/django/start.sh
justfile

I noticed paths were inconsistent, so I matched up the docs.

:whale: Docker hotfix

---

docs/docs/install.md

:books: Adds Rebuild Search Indexs to docs

---

templates/base.html
templates/pages/funding.html

Exposing the funding page and some other projects.

:pencil: Updates footer and funding pages

---

docs/requirements.txt
favorites/tests.py
favorites/tests/test_views.py
favorites/urls.py
favorites/views.py
package/views.py
requirements.in
requirements.txt
settings/base.py
templates/package/package.html
templates/package/partials/favorites.html
urls.py

fixes https://github.com/djangopackages/djangopackages/issues/1213 https://github.com/djangopackages/djangopackages/issues/1212
[Screencast from 2024-07-25 23-15-27.webm](https://github.com/user-attachments/assets/93dedb99-e0a2-4840-8a6c-9f2c67defb20)

favorite and unfavorite view package

---

.devcontainer/devcontainer.json

fixes https://github.com/djangopackages/djangopackages/issues/1231

add git and git cli and precommit in devcontainer

---

package/tests/test_views.py
settings/base.py
templates/package/package.html

fixes https://github.com/djangopackages/djangopackages/issues/1227

favorite package feature flag

---

profiles/forms.py

Fixes https://github.com/djangopackages/djangopackages/issues/1238
Share favorites in profile form

share favorites in profile form

---

static/js/site.js
templates/base.html

closes https://github.com/djangopackages/djangopackages/issues/1256

Add Search Hotkey ("/") for Navbar Search Input

---

settings/base.py
settings/docker.py

:elephant: :tractor: Moves connection pooling to docker settings

---

core/management/commands/init_scheduled_jobs.py
searchv2/builders_v3.py
searchv2/management/commands/searchv3_build.py

Fixes #1278 
@ryancheley it's been a LONG time since I looked at this. I'm fighting allergies/whatever my family gave me crud today, so I need a clear head to remember what my original intent was with the code that's commented out.

:sparkles: Adds searchv3 builder

---

justfile

Our `fab deploy` workflow has never been the most reliable. It was built with Fabric3, which only runs on Python 3.9. 
Thankfully, we only have about another year left before Python 3.9 is end-of-life'ed: https://devguide.python.org/versions/#supported-versions 
So that recipe was rewritten to use UV (I know, you are shocked) because we can have to pull a Python 3.9 version without the project getting too weird. 
While I was here, I touched on a few recipes that can be streamlined more.

:tractor: Expand uv recipes and fix “fab deploy”

---

apiv4/mixins.py
apiv4/serializers.py
apiv4/viewsets.py
docs/docs/apiv4_docs.md
tests/test_viewsets.py

closes https://github.com/djangopackages/djangopackages/issues/1292

[APIv4] Make Grid and Package Detail API accept both `slug` and `pk`

---

README.md
docs/docs/contributing.md
docs/docs/index.md
docs/docs/testing_instructions.md

The `Installation` link was broken i updated it `contributing.md#contributing.md#install-django-packages-locally`
fixed https://github.com/djangopackages/djangopackages/issues/1298

broken link fix

---

package/repos/codeberg.py

fix participant extraction in CodebergHandler

---

searchv2/builders.py
searchv2/builders_v3.py

:tractor: Sort-of fix for Search

---

docs/docs/rules/rules.md
docs/mkdocs.yml

Fixed Docs Build

---

docs/docs/rules/rules.md

:memo: fixed formatting for rules page

---

templates/base.html

:ring: 2025-04-01 Update

---

docs/docs/apiv3_docs.md
docs/docs/apiv4_docs.md

I stumbled on this a bit when I read it, so others might as well. I'm especially thinking of people with English as a 2nd-Nth language.

clarity improvement

---

justfile

I broke some ground on #1379. 
```
Available recipes:
[core]
bump *ARGS                       # Update the version; Used before release to production
fmt                              # Format the justfile
[database]
clearsessions                    # Clear sessions
pg_dump file='db.dump'           # dump database to file
pg_restore file='db.dump'        # restore database dump from file
[deployment]
deploy                           # Deploys to production
purge_cache                      # Purge our CloudFlare cache
[django]
collectstatic *ARGS="--no-input" # Run the collectstatic management command
console                          # Drop into the console on the docker image
createsuperuser USERNAME EMAIL   # Create a Superuser
cron                             # Run all scheduled tasks in …
```

:sparkles: Add justfile recipe comments and grouping recipes
