djangopackages/djangopackages

README.rst
core/apiv1.py
templates/base.html
templates/pages/contribute.html

As per [their blog post of the 27th April](https://blog.readthedocs.com/securing-subdomains/) ‘Securing subdomains’:
> Starting today, Read the Docs will start hosting projects from subdomains on the domain readthedocs.io, instead of on readthedocs.org. This change addresses some security concerns around site cookies while hosting user generated data on the same domain as our dashboard.
Test Plan: Manually visited all the links I’ve modified.

Convert readthedocs links for their .org -> .io migration for hosted projects

---

docs/conf.py
static/error.html
static/maintenance.html
templates/500.html
templates/base.html

I noticed that the year in the footer was out of date so I updated it.
I fixed the templates when I could so that it now automatically displays the current year.
However, I was not able to do that in the static HTML pages (error.html and maintenance.html) so on those pages I just incremented the year.
I also tried to use a dynamic year in the sphinx configuration file but I'm not sure if that's a valid solution.
Thanks!

Fixed copyright year in footer

---

templates/package/package.html

There is no server-side check that the pypi_url does not contain an arbitrary malicious JavaScript. Therefore the attacker can plant a stored XSS flaw as demonstrated in here:
https://djangopackages.org/packages/p/test/

XSS flaw bugfix

---

compose/redis/Dockerfile
dev.yml

Pin redis base image in ./compose/redis/Dockerfile to 3.2 (complying with the one in dev.yml).
Closes #472.

Pin redis image

---

compose/django/Dockerfile-dev
requirements.txt

Hi, I'm submitting a small PR with my changes because I wasn't initially able to build the project locally using Docker. 
I initially got this error trace when trying to build using Docker:
```
Command "/usr/local/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-zkat9xjc/uwsgi/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-lrubmm5h/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-zkat9xjc/uwsgi/
You are using pip version 10.0.1, however version 18.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```
Here are the changes that I made:
1. …

Small changes needed to build Docker locally

---

README.rst

It fixes the broken doc link on the readme `http://djangopackagesorg.readthedocs.io/en/latest` it should be `http://djangopackages.readthedocs.io/en/latest`

Fixed RTD documentation link

---

requirements.txt

Version 2.6.2 of psycopg2 throws and error while building image.
Updated psycopg2 to latest version 2.8.3, and seems that nothing broke

Update psycopg2 to 2.8.3

---

README.rst
docs/install.rst

The .env.local is required to run docker-compose build but the documentation lists the docker-compose build first.
Running build first as mentioned in the quickstart and main documetation returns this error:
```
~/dev/python/djangopackages(master*) » docker-compose -f dev.yml build                                                                                       
ERROR: Couldn't find env file: /Users/hugo/dev/python/djangopackages/.env.local
```
After copying the file there are no issues:
```
~/dev/python/djangopackages(master*) » cp .env.local.example .env.local                                                                                      
------------------------------------------------------------
~/dev/python/djangopackages(master*) » docker-compose -f dev.yml build …
```

[Documentation] The .env.local is required to run docker-compose build

---

requirements.txt

White noise causes pyup to fail due to a security update. Since we are not using it this PR removes it

Remove whitenoise from requirements since we are not using it

---

core/management/commands/load_dev_data.py

NoArgsCommand class is deprecated since django 1.10 also import_module is removed since django 1.9 due to python's builtin importlib. I updated the load_dev_data management command to use new stuff.
This PR fixes https://github.com/djangopackages/djangopackages/issues/534

Fix #534 Remove deprecated stuff and use new ones

---

docs/repo_handlers.rst
package/repos/base_handler.py

There is a small typo in docs/repo_handlers.rst, package/repos/base_handler.py.
Should read `separated` rather than `seperated`.

docs: Fix simple typo, seperated -> separated

---

docker-compose.yml

- Limit containers max log size
- Enable containers log rotation
- Enable containers log compression
By default, [`docker-compose`](https://docs.docker.com/compose/compose-file/#logging) uses json-file as the log driver.
The [`json-file`](https://docs.docker.com/config/containers/logging/json-file/) is configured by default to:
- Allow the container to generate a log file with unlimited size. In practice, the maximum size of the log file will be the maximum size of the disk space.
- not rotate the log files.
- not compress the log files.
Letting the log files grow indefinitely does not seem like a correct choice because, at some point, we will end up completely filling our disk in the middle of the night.
With the configuration of this pull-request and if log compression disabled, the …

Add docker-compose logging configurations

---

requirements.txt

Bump Django and Httplib versions substitute PRs https://github.com/djangopackages/djangopackages/pull/589
https://github.com/djangopackages/djangopackages/pull/586

Bump django and httplib version

---

templates/package/package.html

Added target="_blank" to PyPi and Repo links in the package view. 
Currently browsing packages is a bit annoying when you browsing more of them and you constantly need to right click and open in the new tab.

Added target blank to repo and pypi links

---

README.rst

Changes:
1. Removes `Python3 blockers` badge, like this project is already using Python3, why does it show any blockers?
2. Puts more important badges first, then PyUP with less important info

Reorganizes README badges

---

grid/models.py
grid/views.py

I was fighting cache issues and made a small refactor to help address it. The grid cache gets dumped updates, but we'll have to test it on large grids to see if we have issues.

🚜 Refactors grid template cache to dump on save/delete

---

settings/base.py
urls.py

Django Debug Toolbar already existed but was not appearing in DEBUG mode. References discussion #685
There were mainly two reasons for it to not appear:
- It was not included in urls.py
- Debug toolbar checks if the remote address is in the list of `INTERNAL_IPS` or not and then it is enabled. Since we use docker it was not showing. The detailed explanation can be seen here - https://stackoverflow.com/a/50492036.

Enable Django Debug Toolbar.

---

.env.local.example

Hello!
I recently started to get an error that was blocking my local development with docker: `Postgres is unavailable - sleeping`
I wasn't getting this error when I ran this project a week ago. So after doing some investigation, I was able to run the project again after adding `POSTGRES_HOST` and `POSTGRES_PORT` to `.env.local`. I believe this error was introduced because we forgot to update `.env.example` after this change https://github.com/djangopackages/djangopackages/commit/7d33a613dfc4df9ce48cded8a1d4d046dd6a1352
So I'm creating this PR to include the missing postgres env vars to `.env.local.example`, in order to have everything properly configured before following the README quickstart step  `cp .env.local.example .env.local`

Add missing postgres env vars to env example

---

grid/views.py
static/css/grid.css
templates/grid/grid_detail.html

Adds two filters to grid: **python3** and **stable**.
Refers to: #646
**Changelog:**
- Add filter section in the grid template.
- Add JS to handle query strings, filter change and redirect.
- Add filter variant to the cache template tag.
- Add CSS to render the filter section.
- Add filter to grid detail view.
- Add filter whitelist to prevent cache overflow.
- Serialize sorted filters to prevent cache duplication.
**Important Note:**
With those 2 filters, the total of different templates rendered for each grid increases up to four, one for each possible filter combination.
Using the Authentication grid as an example:
1. `python3=False` and `stable=False` - *all = 117 (current)*
2. `python3=True` and `stable=False` - *python3 = 67 (+57%)*
2. `python3=True` and `stable=True` - *stable …

Issue/646 - Add filters to Grid

---

package/utils.py

This is a follow-up pr for issue #676. 
This PR updates the normalize_license function for classifiers to look for items that start with **"License"**.
It also refactors the function a bit to improve code quality and still maintaining readability.

Follow-up for Update Trove Classifier for Licenses

---

compose/postgres/Dockerfile

Fixes #735 
This upgrades our default (dev.yml) Postgres database from 9.4 to 13.
I highly suggest changing the Dockerfile to use 9.4 to do a backup.sh then switch it back to 13 and run restore in case of any loss.

⬆️🐘 Upgrade dev Postgres from 9.4 to 13

---

dev.yml

This is a fix for local dev environments. We could also map them to a local path + volume but this is fairly close to matching production.

:gear: This fixes our local static volumes

---

.github/workflows/deploy-main.yml

Since the deploy workflow creates a commit on the main branch, the current configuration ends up causing the main branch of a fork to diverge from our main branch, which can hinder the contribution flow.
This pull-request makes the workflow deploy only run automatically in our organization, that is, it will be ignored in forks.

Avoid running the docker image building on forks

---

.github/changelog-template.md
CHANGELOG.md

This PR closes the issue #746. I replaced the `pull_request.url`(api url) for `pull_request.html_url` and fixed the links on the changelog.

Fix changelog links

---

README.rst
dev.yml

- Add namespace to dev docker images and volumes
- Change the Django runserver port to 18000
The basic idea of this pull-request is to avoid having common names for images and volumes on `dev.yml` so that a potential contributor doesn't have to deal with image name collision issues and docker volumes.
It also changed the port used by runserver from 8000 to 18000 for the same reason.

Avoid docker image/volume collision by using a namespace

---

templates/_homepage.html

**Description:**
This PR adds back the Grid of the week panel to the home page.
**_issue:_** https://github.com/djangopackages/djangopackages/issues/720

Grid of the Week panel on the Home page

---

homepage/views.py
templates/_homepage.html

I noticed that the "Random 5" homepage view tends to show only 4 packages. This is because it's assumed that PKs line up with our total packages. We also show depreciated packages which this PR removes.

:bug: fixes query/display bug of Random 5 homepage packages

---

README.rst
docs/contributing.rst
docs/faq.rst
docs/install.rst
docs/management_commands.rst
docs/testing_instructions.rst

Updated commands in documentation files (*.rst) where the command referred to "dev.yml", changing them to "docker-compose.dev.yml".
There were two places referring to this that I didn't change:
* One was in `CHANGELOG.md`, and refers to the name of an issue rather than syntax of a currently used command.
* One was in `.devcontainer/devcontainer.json`, and that seems to be a VS Code config file, that I'm leery of messing with because I'm not currently using VS Code and don't know what this might affect.

update doc references from dev.yml to docker-compose.dev.yml

---

package/tests/data.py

Fix for the test_score failure in #784.
The django-cms package in package/tests/data.py was getting the 30% penalty for not supporting python3. Added supports_python3 to the latest version.

fixes test_score test failure

---

conftest.py

Small update to set up moving settings into a pytest fixture. (also shaves off some testing time.)

:gear: partially use a pytest settings fixture

---

grid/context_processors.py
homepage/tests/test_views.py
homepage/views.py
templates/_homepage.html

The goal here is to cache a few common homepage bits that take longer than we'd like to load.

:rocket: Homepage Cache

---

settings/docker.py

We get tons of `InvalidCursorName` sentry errors with our connection pooling so changing this up to see if they go away:
https://docs.djangoproject.com/en/4.1/ref/databases/#transaction-pooling-and-server-side-cursors

:gear: set DISABLE_SERVER_SIDE_CURSORS to True

---

grid/forms.py
grid/views.py
static/css/grid.css
templates/grid/grid_detail.html

This Pull Request:
- Adds option to sort Grid Packages by `downloads`, `watchers`, `forks`, `last_commit_date` and `score` (default)
- Refactors the filters to use Django Forms
- Removes CSS and JavaScript that are not required anymore
closes https://github.com/djangopackages/djangopackages/issues/199

Add Option to Sort Grid Packages

---

static/angular/controllers.js
templates/base.html

AngularJS raises an exception when `emojificate` templatetag is used inside search results `ng-repeat` Directive.
**Console output:**
```console
Error: Unknown provider: emojifyFilterProvider <- emojifyFilter
at angular.min.js:29:439
at Object.c [as get] (angular.min.js:27:142)
at angular.min.js:30:21
at Object.c [as get] (angular.min.js:27:142)
at angular.min.js:109:235
at u (angular.min.js:70:141)
at w (angular.min.js:75:72)
at l (angular.min.js:69:507)
at Rc (angular.min.js:75:170)
at angular.min.js:78:426
```
closes https://github.com/djangopackages/djangopackages/issues/862

Fix Global Search

---

core/templatetags/typogrify_tags.py
templates/_homepage.html
templates/homepage.html

Adds "widont" support to avoid hanging words on the homepage, which is where it annoys me the most. 
The `django-typogrify` is currently not supported for Django 4.0, so I pulled in just what we needed. It has some other useful tags in it though too.

✨ Add widont support

---

docs/conf.py
docs/contributing.rst
docs/deployment/docker.rst
docs/index.rst

- Adds Logo to Documentation
- Adds Sidebar to Documetation
- Fixes Bullet List Warning (`Bullet list ends without a blank line`)
- Removes nonexistent references from `toctree` (`toctree contains reference to nonexisting document`)
- Fixes `:doc:` reference issue. (`unknown document: 'installation'`)

Add Sidebar and Logo for Documentation Page

---

docs/license.md

I've kept the original `rst` version of the file.

:books: Added markdown version of license

---

.github/FUNDING.yml
homepage/views.py
templates/pages/open.html

This removes our `FUNDING.yml` page, and it's something we can address/figure out an org at some point.
I added a few charts to /open/ with the intent to start documenting monthly/annual expenses for running the website. I have hosting, domain registration, and ethical adds income listed. Ideally, this could be a Django model and be expanded.

📈  Funding updates

---

.github/CONTRIBUTORS-template.md
CONTRIBUTORS.md
README.md
core/apiv1.py
templates/base.html
templates/pages/faq.html

This moves our default docs home/location to https://docs.djangopackages.org/en/latest/

:tractor: Updates docs domain

---

.devcontainer/create_dot_env.sh
.devcontainer/devcontainer.json
.devcontainer/docker-compose.yml
.vscode/launch.json
.vscode/settings.json

**This PR**
- Adds Launch Configuration for `mkdocs` Documentation
- Fixes Launch Configuration for `pytest`
- Removes Deprecated/Removed Options from Dev Containers Configuration file.
**PyCharm Support**
PyCharm does not have support for dev containers. Discussion: https://youtrack.jetbrains.com/issue/IDEA-202267
**Tested in**
- Linux (Ubuntu)
- GitHub Codespaces
closes https://github.com/djangopackages/djangopackages/issues/942

Update VSCode Dev Containers

---

.github/CONTRIBUTORS-template.md
CONTRIBUTORS.md
README.md
core/apiv1.py
templates/base.html
templates/pages/faq.html

With the recent move to Mkdocs, all of the links to the documentation were broken as the `.html` file ending is not handled by it.

Fix broken links to documentation

---

justfile
templates/base.html
templates/pages/faq.html

Updates footer copy (kept all OG attribution) but also adds DO link and links to the GH contributors instead of the docs copy (which might break)

:pencil: Update contributor attribution and FAQs

---

.pre-commit-config.yaml
homepage/tests/test_views.py
homepage/views.py

I was annoyed at seeing blank `repo_description`s on the homepage. 
I left the latest packages as-is to avoid not seeing new packages.

:hammer: Remove packages from the homepage with blank repo_descriptions

---

.dockerignore

I'm not sure how we went this long without a `.dockerignore` file and yet here we are...

:whale: Adds a .dockerignore file

---

templates/grid/grid_detail.html
templates/package/category.html
templates/package/package.html
templates/package/python3_list.html

Install Carbon Ads on the site. Each page will have a different zone key to track the impressions and performance separately. Some of the containers have been set to `col-lg-12` to make sure they look okay on the mobile devices.
@jefftriplett can you run it locally to see if there are any issues with the layout? I can move the ad and update the CSS if you have any preferences.

Add Carbon Ads

---

docker-compose.prod.yml
docker-compose.yml

With this we should be able to run:
```shell
12 23 * * * /usr/bin/docker compose -f /code/djangopackages/docker-compose.prod.yml --profile utility run --rm utility python manage.py searchv2_build
36 17 * * * /usr/bin/docker compose -f /code/djangopackages/docker-compose.prod.yml --profile utility run --rm utility python manage.py package_updater
48 21 * * * /usr/bin/docker compose -f /code/djangopackages/docker-compose.prod.yml --profile utility run --rm utility python manage.py pypi_updater
```
closes: https://github.com/djangopackages/djangopackages/issues/961

Add Utility Service to Run CronJobs

---

core/management/commands/init_scheduled_jobs.py
fabfile.py
requirements.in
requirements.txt
settings/base.py

Reference https://github.com/djangopackages/djangopackages/issues/961
TODO: 
- Remove References to cron job (we can either do this on this PR or try the new changes out first)

Move cron jobs to `django-q` scheduled tasks

---

.github/workflows/actions.yml
.pre-commit-config.yaml
docs/docs/install.md
docs/docs/install_opinionated.md
fabfile.py
justfile
pyproject.toml

Reference: https://docs.astral.sh/ruff/formatter/

Move to Ruff Formatter

---

docs/docs/faq.md
docs/docs/install.md
docs/docs/install_opinionated.md

It made more sense to move Load Sample Data Instruction to Installation Page rather than keeping it on the FAQ page. This makes it easy to discover Load Sample Data Instructions
PR Doc Build: https://djangopackages--1048.org.readthedocs.build/en/1048/install/

Move Load Sample Data Instructions to Installation Page

---

homepage/tests/test_views.py
homepage/views.py
templates/_homepage.html
templates/homepage/django_package_of_the_week_partial.html
templates/homepage/public_service_announcement_partial.html

The PR adds a few feature switches around the Gride of the Week + Package of the Week. The PSF flag is primarily a place holder until we swap out some copy.

:sparkles: Feature flag grid and package of the week + psa

---

profiles/admin.py

The Django admin isn’t happy with autocomplete_fields set with 18k users. Switching to raw_id_fields.

:tractor: Adds raw_id_fields to Profile

---

grid/templatetags/grid_tags.py
package/tables.py
package/utils.py
static/js/svg-sparkline.js
templates/base.html
templates/grid/grid_detail.html
templates/grid/grid_detail_landscape.html
templates/grid/snippets/_commits.html
templates/package/includes/_commits.html
templates/package/package.html

closes https://github.com/djangopackages/djangopackages/issues/1128
I was able generate this image URL (DRF Commit Graph) using the script on the PR.
> `https://quickchart.io/chart?width=105&height=20&chart=%7B%22type%22%3A%22bar%22%2C%22data%22%3A%7B%22labels%22%3A%5B1%2C1%2C4%2C1%2C4%2C1%2C2%2C2%2C6%2C3%2C0%2C1%2C1%2C1%2C3%2C0%2C1%2C8%2C0%2C1%2C0%2C2%2C0%2C0%2C4%2C2%2C3%2C0%2C0%2C1%2C0%2C0%2C3%2C1%2C0%2C0%2C0%2C4%2C1%2C1%2C5%2C2%2C0%2C1%2C5%2C3%2C4%2C3%2C7%2C10%2C1%2C1%5D%2C%22datasets%22%3A%5B%7B%22data%22%3A%5B1%2C1%2C4%2C1%2C4%2C1%2C2%2C2%2C6%2C3%2C0%2C1%2C1%2C1%2C3%2C0%2C1%2C8%2C0%2C1%2C0%2C2%2C0%2C0%2C4%2C2%2C3%2C0%2C0%2C1%2C0%2C0%2C3%2C1%2C0%2C0%2C0%2C4%2C1%2C1%2C5%2C2%2C0%2C1%2C5%2C3%2C4%2C3%2C7%2C10%2C1%2C1%5D%2C%22backgroundColor%22%3A%22%23666666%22%2C%22borderWidth%22%3A1%7D%5 …

Replace Google Chart with `svg-sparkline.js` for Commit Chart Generation

---

templates/profiles/profile.html

I verified that `rel="nofollow"` is included for free. 
```html
<p><b>Mastodon:</b> <a href="https://mastodon.social/@webology" rel="nofollow">https://mastodon.social/@webology</a></p>
 ```

:art: urlize extra field url value

---

package/tables.py
package/views.py

This fixes out #1 Sentry bug a month. 
```
{'code': 500, 'request': 'GET /python3/?dir=asc&page=82&sort=-usage_count', 'event': 'request_fai...
```

:bug: Fix broken python3 using this filter

---

apiv3/views.py

I'm leaving this api in but requiring auth after seeing too many API 500 errors. I'm not a fan of having an open api endpoint for things like users.

:fire: Remove user api crawling

---

docs/docs/apiv4_docs.md
docs/mkdocs.yml

PR Docs Build URL: https://djangopackages--1165.org.readthedocs.build/en/1165/apiv4_docs/

[DOCS] Add APIv4 Documentation

---

compose.yml
justfile

This adds a few convenience `just` recipes:
- `just pg_dump`
- `just pg_restore`
It also exposed the `/app` volume to the database service container so that we can see backup files.

:elephant: Adds pg_dump and pg_restore recipes

---

searchv2/rules.py

Fixed a bug when running `python -m manage searchv3_build` with only `load_dev_data` generated data in the database.

:bug: Fixes a last_updated is None issue

---

profiles/tests/test_views.py
profiles/views.py
templates/profiles/profile.html

- Modify user profile view to:
- Retrieve the user's favorite packages if share_favorites is True.
- Add the list of favorite packages to the context data.
- Update the user profile template to display the favorite packages.
Fixes #1214 
(In draft because I have problems running unit tests in my local environment)

Favorite Packages: Modify User Profile view

---

templates/profiles/profile.html

fixes https://github.com/djangopackages/djangopackages/issues/1243
The grid column is removed if the package does not exist.

Profile view update

---

homepage/views.py
templates/pages/open.html

Updates to prep for tracking Django 5.1 and Python 3.13. 
- https://djangopackages.org/open/
- https://djangopackages.org/readiness/

:arrow_up: Bumps for Django 5.1 and Python 3.13

---

homepage/views.py

Workaround for https://djangopackages.org/readiness/ until we get stable download stats.

:pencil: Updates repo_watchers

---

templates/grid/grid_detail.html

This PR adds overflow scrollbar for large grids, which used to break the UI.
**Example:** https://djangopackages.org/grids/g/admin-interface/
**Before:**
**After:**

Fix Large Grid Display Issue

---

pyproject.toml

Fixes #1235 
`--reuse-db` is a nice default but it trips anyone who is new up when a database change doesn't get applied.

:fire: Removes `--reuse-db` testing option

---

fabfile.py

This was tripping up a production cron issue that wasn't obvious. The `django-a` and `django-b` services were rebuilding, but the `utility` service wasn't getting a newer profile to rebuild.

:gear: :whale: Adds missing `--profile` option

---

package/management/commands/pypi_stats.py

Production test for #1289 
Locally, I run `pypi_stats` without a delay, but in production we can only get one request off before being throttled. 
We intend to be good citizens, but I was surprised to find that the two environments differ so much. 
The limit appears to be `"5 per second", or "30 per minute,"` so a 5-second delay should be plenty. 
https://github.com/crflynn/pypistats.org/blob/70a10f994173b4b9e8905fb3494dd5d0d5bd1bbb/pypistats/run.py#L23

✨ Adds delay option to pypi_stats

---

core/context_processors.py
grid/tests/test_views.py
grid/views.py
package/tests/test_views.py
settings.py
templates/base.html
templates/grid/grid_detail.html
templates/package/package.html

**Description:**
Adding the "Score" to both the Grid and Package detail pages.
**Issue:**
https://github.com/djangopackages/djangopackages/issues/1063
**Screenshots:**
Grid Detail page:
https://github.com/user-attachments/assets/f7d6c037-c71d-4b67-b3ef-7112f88e5dc9
Package Detail page:
https://github.com/user-attachments/assets/ecafd97d-0268-4bb4-80c0-31a80250dfc1
**Open questions:**
1. Should I use the `{% static <path-to-asset>%}` or the {{ STATIC_URL }}? I saw places where one or the other is being used.
2. I'm not the biggest fan of testing HTML content without test markup, such as a `data-test-id` attribute in the tag, to avoid false positives and flakiness when asserting that the content I expected is in the correct place. Do you have any objections to adding it to this PR?
3. Can …

Integrate score value into Package/Grid results #1063

---

package/repos/codeberg.py

Fixes #1324
We are occasionally getting an error on `commit["author"]["login"]` because Codeberg is returning `None`.

🔥 Updates Codeberg User reference
